[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
DEBUG = "false"
HOST = "0.0.0.0"
PORT = "8000"
LOG_LEVEL = "INFO" 