services:
  - type: web
    name: real-estate-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: VWORLD_API_KEY
        sync: false
      - key: BUILDING_API_KEY
        sync: false
      - key: LAND_API_KEY
        sync: false
      - key: LAND_REGULATION_API_KEY
        sync: false
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health